version: "3.8"

services:

    quarkustwitter:
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
        container_name: quarkustwitter
        ports:
            - "8080:8080"
        depends_on:
            - mongodatabase

    mongodatabase:
        image: mongo:5.0.25-focal
        container_name: mongodatabase
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - "27017:27017"
        command: mongod

volumes:
    mongodb:
    mongodb_config: